config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                                    sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    passwords: 'users/passwords'
                                  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount ActionCable.server => '/cable'

  devise_scope :user do
    root to: "users/sessions#new"
  end

  resources :projects, only: [:index]
  resources :sprints, only: [:index]
  resources :session, only: [:index]
  resources :tasks, only: [:index, :update] do
    get :task_description
    post :play
    post :pause
    post :transfer
    post :add_comment
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  private
  attr_reader :get_project, :get_sprint, :get_tasks, :start_task,
    :stop_task, :transfer_task, :update_task,
    :get_task_description, :get_comments, :add_task_comment,
    :get_users, :get_team

  before_action :provide_get_project,          only: [:index]
  before_action :provide_get_sprint,           only: [:index]
  before_action :provide_get_tasks,            only: [:index]
  before_action :provide_get_users,            only: [:index]
  before_action :provide_get_team,             only: [:index]
  before_action :provide_update_task,          only: [:update]
  before_action :provide_start_task,           only: [:play]
  before_action :provide_stop_task,            only: [:pause]
  before_action :provide_transfer_task,        only: [:transfer]
  before_action :provide_get_task_description, only: [:task_description]
  before_action :provide_get_comments,         only: [:task_description]
  before_action :provide_add_task_comment,     only: [:add_comment]

  def provide_get_project
    @get_project = ::Injections::UseCase.provide_get_project(logged_user)
  end
  
  def provide_get_sprint
    @get_sprint = ::Injections::UseCase.provide_get_sprint(logged_user)
  end

  def provide_get_tasks
    @get_tasks = ::Injections::UseCase.provide_get_tasks(logged_user)
  end

  def provide_get_users
    @get_users = ::Injections::UseCase.provide_get_users(logged_user)
  end

  def provide_get_team
    @get_team = ::Injections::UseCase.provide_get_team(logged_user)
  end

  def provide_update_task
    @update_task = ::Injections::UseCase.provide_update_task(logged_user)
  end

  def provide_start_task
    @start_task = ::Injections::UseCase.provide_start_task(logged_user)
  end

  def provide_stop_task
    @stop_task = ::Injections::UseCase.provide_stop_task(logged_user)
  end

  def provide_transfer_task
    @transfer_task = ::Injections::UseCase.provide_transfer_task(logged_user)
  end

  def provide_get_task_description
    @get_task_description = ::Injections::UseCase.provide_get_task_description(logged_user)
  end

  def provide_get_comments
    @get_comments = ::Injections::UseCase.provide_get_comments(logged_user)
  end

  def provide_add_task_comment
    @add_task_comment = ::Injections::UseCase.provide_add_task_comment(logged_user)
  end

  public
  def index
    user_id   = params[:user_id]
    sprint_id = params[:sprint_id].to_i
    @sprint   = get_sprint.sprint(sprint_id)
    @project_name = get_project.project(@sprint.project_id).name

    get_tasks.tasks({user_id: user_id, sprint_id: sprint_id}, {
      on_success: -> (tasks, delivered_tasks) {
        @total_of_delivered_tasks = delivered_tasks.size
        @total_of_tasks           = tasks.size + @total_of_delivered_tasks
        @tasks_times              = TasksTimesPresenter.new(tasks, delivered_tasks)
        @tasks_by_state           = TasksByStatePresenter.new tasks, delivered_tasks

        team_id = tasks.present? ? tasks.first.team_id : nil

        @team_users = []
        get_team.team({team_id: team_id}, {
          on_success: -> (team) {
            @team_users = get_users.users(team.user_ids)
          },
          on_error: -> (error) { raise error }
        })

        flash[:alert] = nil
      },
      on_error: -> (error) { raise error }
    })
  end

  def task_description
    @task_id = params[:id]

    get_task_description.find_task_description({task_id: @task_id}, {
      on_success: -> (task_description)  {
        @task_description = task_description
      },
      on_error:   -> (error) { raise error }
    })

    get_comments.all_by_task({task_id: @task_id}, {
      on_success: -> (comments)  {
        @task_comments = comments
      },
      on_error:   -> (error) { raise error }
    })

  end

  def update
    task_id = params[:id]
    task_state_sym = params['task']['task_state_sym'].to_sym
    parameters = {task_id: task_id, task_state_sym: task_state_sym}
    update_task.change_state(parameters, {
      on_success: -> (task) {
        ActionCable.server.broadcast 'task_change_state',
        user_id: task.responsible_id,
        task_id: task_id,
        task_state: task_state_sym
      },
      on_error: -> (error) { raise error }
    })
  end

  def play
    task_id = params[:id]
    start_task.start({task_id: task_id}, {
      on_success: -> (task)  { ActionCable.server.broadcast('task_play', task_id: task.id) },
      on_error:   -> (error) { raise error }
    })
  end

  def pause
    task_id = params[:id]
    task_id = params[:id]
    stop_task.stop({task_id: task_id}, {
      on_success: -> (task)  { ActionCable.server.broadcast('task_pause', task_id: task.id) },
      on_error:   -> (error) { raise error }
    })
  end

  def transfer
    task_id        = params[:task_id]
    responsible_id = params[:responsible_id]
    team_id        = params[:team_id]
    parameters = {task_id: task_id, responsible_id: responsible_id, team_id: team_id}

    transfer_task.transfer(parameters, {
      on_success: -> (task)  {
        @task_id        = task.id
        @responsible_id = task.responsible_id
      },
      on_error:   -> (error) { raise error }
    })
  end

  def add_comment
    @task_id = params[:task_id]
    text     = params[:text]

    parameters = {task_id: @task_id, text: text}

    add_task_comment.add_comment(parameters, {
      on_success: -> (comment)  {
        @comment = comment
      },
      on_error:   -> (error) { raise error }
    })
  end

end

app/helpers/task_helper.rb
module TaskHelper

  def get_responsible_from_team_users(responsible_id, team_users)
    team_users.find { |user| user.id == responsible_id }
  end

end

app/views/tasks/_board.html.erb
<div>
    <div class="board-title"> <%= title %> </div>
    <section class="board" id="<%= board_id %>" data-task-status-sym="<%= task_status_sym %>">


      <div class="board-scroll">

        <% tasks.each do |task|  %>
          <%= render partial: 'details_modal', locals: {task: task, team_users: team_users} %>
          <%= render partial: 'card', locals: {task: task} %>
        <% end %>

      </div>

    </section>
</div>

app/views/tasks/_card.html.erb
<article class="card <%= "card-user-played" if task.is_working_on %>"
  id="<%= task.id  %>" draggable="true">

  <article class="card-click-details" data-task-id="<%= task.id %>">
    <div class="<%= "disapproved" if task.is_disapproved? %>"></div>
    <div class="detail">
      <%= image_tag(get_responsible_from_team_users(task.responsible_id, @team_users).avatar_url,
                    size: '25x25', class: 'hvr-glow userslist-face-round-card') %>
      <span class="task-id">#<%= task.id  %></span>
    </div>
    <header class="centered-text"><%= task.title  %></header>
  </article>

  <a type="button" id="btn-task-play-<%= task.id %>"
    class="task-play <%= "hidden" if task.is_working_on %>"
    data-task-id="<%= task.id %>"
    data-task-title="<%= task.title %>"
    ><span class="glyphicon glyphicon-play btn-play"></span></a>

  <a type="button" id="btn-task-pause-<%= task.id %>"
    class="task-pause <%= "hidden" unless task.is_working_on %>"
    data-task-id="<%= task.id %>"
    data-task-title="<%= task.title %>"
    ><span class="glyphicon glyphicon-pause btn-pause"></span></a>

</article>

app/views/tasks/_comment.html.erb
<div>
  <small><b><%= comment.commenter_name %></b></small>
  <p><%= raw comment.text %></p>
</div>

app/views/tasks/_comments.html.erb
<div class="kk-task-details-comments">
  <div class="kk-font-size-12 all-comments-<%= task_id %>">
    <% task_comments.each do |comment| %>
      <%= render partial: 'tasks/comment', locals: {comment: comment}  %>
    <% end %>
  </div>
</div>
<br>
<div>
  <%= form_tag(task_add_comment_path(task_id), remote: true) do %>
    <div class="form-group">
      <%= text_area_tag "text", nil, id: "comment-text-#{task_id}", size: '10x10', class: 'form-control kk-details-task-modal-textarea' %>
    </div>
    <div class="text-center">
      <%= submit_tag 'Comment', class: 'btn btn-sm btn-success' %> <br><br>
    </div>
  <% end %>
</div>

app/views/tasks/_details_modal.html.erb
<div class="modal fade bs-example-modal-lg" id="task-details-modal-<%= task.id %>"
     tabindex="-1" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-body kk-task-details-modal-body">
        <div class="row kk-task-details-modal-row">

          <div>
            <div class="col-lg-6 kk-task-details-modal-side1">
              <br>
              <div class="kk-padding-right-left-content">
                <%= form_tag(task_transfer_path(task.id), remote: true) do %>
                  <div class="text-center kk-details-task-transfer">
                    <%= hidden_field_tag 'team_id', task.team_id  %>
                      <span>Transfer to:</span>
                      <%= select_tag 'responsible_id', options_from_collection_for_select(team_users, :id, :name) %>
                    <%= submit_tag 'Transfer', class: 'btn btn-sm btn-success text-center' %>
                  </div>
                <% end %>

                <div>
                  <br><br>
                  <p id="task-comments-<%= task.id %>"></p>
                </div>
              </div>
            </div>

            <div class="col-lg-6 kk-task-details-modal-side2">
              <br>
              <button type="button" class="close kk-task-btn-close-modal" data-dismiss="modal" aria-label="Close">
                <span class="kk-close" aria-hidden="true">x</span>
              </button>
              <div class="kk-padding-right-left-content">
                <div class="text-center">
                  <h5>#<%= task.id  %> - <%= task.title  %></h5>
                </div>
                <br>
                <div class="kk-task-details-modal-description">
                  <p class="kk-font-size-12" id="task-description-<%= task.id %>"></p>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/tasks/add_comment.js.erb
$('#comment-text-' + '<%= @task_id %>').val('');

var comment_partial = '<%= j render partial: 'tasks/comment', locals: {comment: @comment} %>';
$('.all-comments-' + <%= @task_id  %>).prepend(comment_partial);

app/views/tasks/index.html.erb
<body class="body-grey">
  <!-- Whole Page Wrapper (Sidebar Component) -->
  <div id="wrapper">

    <!-- BACK BUTTON OF SIDEBAR -->


    <div class="glyphicon glyphicon-arrow-right back-btn"></div>

    <!-- Sidebar -->
    <div id="sidebar-wrapper" class="kk-fixed">
      <ul class="sidebar-nav">
        <li>
          <a class="sidebar-brand" href="#">New Task from Calazans</a>
        </li>
        <li>
          <a class="sidebar-brand" href="#">Last day to finish #2873</a>
        </li>
        <li>
          <a class="sidebar-brand" href="#">Transfered task from Eris</a>
        </li>
        <li>
          <a class="sidebar-brand" href="#">Forgot to pause task #2255</a>
        </li>
        <li>
          <a class="sidebar-system" href="#">Profile</a>
        </li>
        <li>
          <a href="#">

            <!-- Logout in the Right Menu -->
            <%= link_to 'Logout', destroy_user_session_path, :method => :delete, class: 'sidebar-system' %>
            <!-- End of logout -->

          </a>
        </li>
      </ul>
    </div>
    <!-- NavBar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">

        <div class="navbar-header">

          <div class="navbar-brand" href="#">
            <%= link_to projects_path() do %> Projects <% end %> /
            <%= @project_name  %> /
            <%= link_to sprints_path(project_id: @sprint.project_id) do %> Sprints <% end %>
          <span class="navbar-brand-bread" href="#">/ <%= @sprint.name  %></span>
          </div>

        </div>



        <!-- Task Counter Navbar -->

        <div class="kk-navbar-dashboard kk-green" href="#">
          <span class="glyphicon glyphicon-tasks kk-navbar-iconfix"></span> <%= @total_of_delivered_tasks %>/<%= @total_of_tasks %>
        </div>


        <div class="kk-navbar-dashboard kk-green">

          <span class="glyphicon glyphicon-hourglass kk-navbar-iconfix"></span> <%= @tasks_times.worked_time_in_hours %>/<%= @tasks_times.estimated_time_in_hours %>h
        </div>

        <!-- User Photo -->
        <div class="kk-green-square">
        </div>
        <ul class="userphoto hvr-backward">
          <a href="#menu-toggle" id="menu-toggle">
            <% if logged_user.present? %>
            <div class="avatar">
              <%= image_tag(logged_user.avatar_url, size: '50x50') %>
            </div>
            <% end %>

          </a>
        </ul>
        <!-- Notification Bell -->
        <ul id="sidebar-wrapper">
          <div class="notification-bg">
            <a href="#" id="menu-toggle">
              <span class="glyphicon glyphicon-bell notification-bell"></span>

              <!-- Username after avatar -->
              <% if logged_user.present? %>
              <div class="username">
                <span><%= logged_user.name %></span>
              </div>
              <% end %>


            </a>
          </div>
        </ul>
      </div>
    </nav>
  </div>

  <!-- Task Ordering -->
  <div class="board-middle">


    <span class="clicked-tasks board-middle-tasks" href="#"><%= link_to tasks_path(sprint_id: @sprint.id, user_id: logged_user.id) do %> Show My Tasks <% end %></span>


    <span class="clicked-tasks board-middle-tasks"><%= link_to tasks_path(sprint_id: @sprint.id) do %> Show All Tasks <% end %></span>


    <!-- <a class="board-middle-tasks" href="#">Other Tasks</a> -->

  </div>


  <!-- KanKan Cards -->
  <!-- Userslist -->

  <div class="board-middle-users">
    <div class="userslist-bg userslist-face-round">

      <% @team_users.each do |user| %>
      <%= link_to tasks_path(sprint_id: @sprint.id, user_id: user.id) do %> <%= image_tag(user.avatar_url, size: '40x40', class: 'hvr-float') %>
      <% end %>
      <% end %>

    </div>
  </div>
  <!-- Userslist end -->
  <h1 class="kk-green"><%= flash[:alert] %></h1>

  <h4>
    <% @team_users.each do |user| %>
    <%= link_to tasks_path(sprint_id: @sprint.id, user_id: user.id) do %> <% end %>
    <% end %>
  </h4>
  <section class="boards">

    <%= render partial: 'board',
    locals: {
      tasks: @tasks_by_state.todo,
      team_users: @team_users,
      title: 'To Do',
      board_id: 'to_do',
      task_status_sym: 'to_do'
    }
    %>

    <%= render partial: 'board',
    locals: {
      tasks: @tasks_by_state.in_progress,
      team_users: @team_users,
      title: 'In Progress',
      board_id: 'doing',
      task_status_sym: 'doing'
    }
    %>

    <%= render partial: 'board',
    locals: {
      tasks: @tasks_by_state.in_review,
      team_users: @team_users,
      title: 'On Review',
      board_id: 'on_review',
      task_status_sym: 'on_review'
    }
    %>

    <%= render partial: 'board',
    locals: {
      tasks: @tasks_by_state.approved_in_review,
      team_users: @team_users,
      title: 'Approved On Review',
      board_id: 'approved_on_review',
      task_status_sym: 'approved_on_review'
    }
    %>

    <%= render partial: 'board',
    locals: {
      tasks: @tasks_by_state.on_stage,
      team_users: @team_users,
      title: 'On Stage',
      board_id: 'on_stage',
      task_status_sym: 'on_stage'
    }
    %>

    <%= render partial: 'board',
    locals: {
      tasks: @tasks_by_state.approved_on_stage,
      team_users: @team_users,
      title: 'Approved On Stage',
      board_id: 'approved_on_stage',
      task_status_sym: 'approved_on_stage'
    }
    %>

    <%= render(partial: 'board',
    locals: {
      tasks: @tasks_by_state.on_production,
      team_users: @team_users,
      title: 'On Production',
      board_id: 'delivered',
      task_status_sym: 'delivered'
      }) if logged_user.is_master || logged_user.is_manager
      %>

      <%= render(partial: 'board',
      locals: {
        tasks: @tasks_by_state.cloned_to_next_sprint,
        team_users: @team_users,
        title: 'Cloned to Next Sprint',
        board_id: 'cloned_to_next_sprint',
        task_status_sym: 'cloned_to_next_sprint'
        }) if logged_user.is_master || logged_user.is_manager
        %>

      </section>


      <script>
      $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
      });
      </script>
    </body>

app/views/tasks/task_description.js.erb
$('#task-description-' + <%= @task_id  %>).html('<%= j(raw @task_description.description)  %>');
var comments_page = '<%= j render partial: 'tasks/comments', locals: {task_id: @task_id, task_comments: @task_comments} %>';
$('#task-comments-' + <%= @task_id  %>).html(comments_page);
$('#task-details-modal-' + <%= @task_id  %>).modal();

app/views/tasks/transfer.js.erb
$('.card-current-responsible-<%= @task_id  %>').html('<%= @responsible_id %>')
$.modal.close();